import {ArrowDownRight,ArrowUpRight,Boxes,Plus,ShoppingCart,TriangleAlert,WalletCards} from 'lucide-react';
import PharmacyNav from '../../features/pharmacy/components/PharmacyNav';
import MedicineCard from '../../features/pharmacy/components/MedicineCard';
import OrderTable from '../../features/pharmacy/components/OrderTable';
import {pharmacyService} from '../../features/pharmacy/services/pharmacyService';
import {inventoryService} from '../../features/pharmacy/services/inventoryService';
import {orderService} from '../../features/pharmacy/services/orderService';

export default function PharmacyDashboard(){const summary=inventoryService.getSummary(); const lowStock=pharmacyService.getLowStock(); const orders=orderService.getRecent(); return <div className="pharmacy-shell"><PharmacyNav/><main className="pharmacy-main"><header className="pharmacy-header"><div><span className="eyebrow">THURSDAY, 27 AUGUST 2026</span><h1>Good morning, Amina</h1><p>Here is today’s view of your pharmacy.</p></div><button className="red-btn"><Plus size={18}/> Add medicine</button></header><section className="pharmacy-stats"><Stat icon={Boxes} label="Total medicines" value={summary.products.toString()} change="6.8%"/><Stat icon={ShoppingCart} label="Open orders" value={orderService.getOpenCount().toString()} change="12.5%"/><Stat icon={WalletCards} label="Today’s sales" value="KSh 48,260" change="9.4%"/><Stat icon={TriangleAlert} label="Needs attention" value={(summary.lowStock+summary.outOfStock).toString()} change="" warning/></section><section className="pharmacy-grid"><div className="pharmacy-panel pharmacy-wide"><div className="panel-head"><div><h2>Stock alerts</h2><p>Medicines that need your attention</p></div><a href="/pharmacy/inventory">View inventory <ArrowUpRight size={16}/></a></div><div className="medicine-cards">{lowStock.slice(0,3).map((medicine)=><MedicineCard medicine={medicine} key={medicine.id}/>)}</div></div><div className="pharmacy-panel sales-snapshot"><div className="panel-head"><div><h2>Sales snapshot</h2><p>Last 7 days</p></div></div><strong className="sales-total">KSh 284,500</strong><span className="sales-change"><ArrowUpRight size={14}/> 15.8% vs last week</span><div className="sales-chart"><i style={{height:'46%'}}/><i style={{height:'64%'}}/><i style={{height:'52%'}}/><i style={{height:'78%'}}/><i style={{height:'69%'}}/><i style={{height:'92%'}}/><i style={{height:'84%'}}/></div><div className="chart-labels"><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span></div></div></section><section className="pharmacy-panel"><div className="panel-head"><div><h2>Recent orders</h2><p>Latest prescription orders from your pharmacy</p></div><a href="/pharmacy/orders">View all <ArrowUpRight size={16}/></a></div><OrderTable orders={orders}/></section><div className="pharmacy-footnote"><span><TriangleAlert size={15}/> {summary.outOfStock} medicine out of stock</span><span>Last synced just now</span></div></main></div>}

function Stat({icon:Icon,label,value,change,warning}:{icon:typeof Boxes;label:string;value:string;change:string;warning?:boolean}){return <article className={`pharmacy-stat ${warning?'warning':''}`}><div className="stat-icon"><Icon size={19}/></div><span>{label}</span><strong>{value}</strong>{change?<small><ArrowDownRight size={13}/> {change} this week</small>:<small>Requires review</small>}</article>}
