import {Link,useParams} from 'react-router-dom';
import {ArrowUpRight,CalendarDays,ClipboardList,Clock3,FileText,HeartPulse,MessageSquare,Plus,Receipt,Stethoscope,Users,Wallet} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
import Sidebar from '../components/Sidebar';
import Topbar from '../components/Topbar';

const stats: [string,string,string,LucideIcon,string][]=[['Total Patients','1,284','+12.4%',Users,'patients'],['Appointments','48','+8.2%',CalendarDays,'appointments'],['Payments','KSh 284,500','+15.8%',Wallet,'payments'],['Open Encounters','17','Today',ClipboardList,'records']];
const activities=[['New patient registered — SAIED-PAT-001284','patients'],['Consultation completed — SAIED-ENC-000921','records'],['Payment received — SAIED-PAY-004521','payments'],['Prescription issued — SAIED-RX-001902','prescriptions']];
const roleSummaries: Record<string,string>={patient:'Manage appointments, records, prescriptions and care conversations.',doctor:'Review assigned patients, encounters and prescribing tasks.',nurse:'Coordinate assigned care, observations and appointments.',pharmacist:'Review prescriptions, dispensing tasks and medicine safety.',clinic:'Coordinate patients, encounters, billing and staff workflows.',hospital:'Monitor departments, encounters, billing and patient flow.',laboratory:'Track tests, samples, results and verification tasks.'};

export default function DashboardInteractive(){const {role='patient'}=useParams(); const summary=roleSummaries[role]||'Manage your secure healthcare workspace.'; const dashboardPath=`/dashboard/${role}`; return <div className="app-shell"><Sidebar role={role}/><div className="main-area"><Topbar role={role}/><main className="dashboard"><div className="dash-head"><div><span className="eyebrow">SAIED {role.toUpperCase()} PORTAL</span><h1>Good morning, SAIED User</h1><p>{summary}</p></div><Link className="red-btn" to={`${dashboardPath}/records`}><Plus size={18}/> New record</Link></div><section className="stats">{stats.map(([name,value,change,Icon,section])=><Link className="stat" to={`${dashboardPath}/${section}`} key={name}><div className="stat-top"><span>{name}</span><div className="stat-icon"><Icon size={19}/></div></div><strong>{value}</strong><small><ArrowUpRight size={14}/>{change}</small></Link>)}</section><section className="dash-grid"><article className="panel wide"><div className="panel-head"><div><h2>Recent activity</h2><p>Latest events in your workspace.</p></div><Link className="more" to={`${dashboardPath}/records`} aria-label="View medical records"><ArrowUpRight size={18}/></Link></div><div className="activity-list">{activities.map(([activity,section],index)=><Link className="activity" to={`${dashboardPath}/${section}`} key={activity}><div className="activity-icon"><HeartPulse size={17}/></div><div><strong>{activity}</strong><span>{index+1} hour{index?'s':''} ago</span></div><Clock3 size={16}/></Link>)}</div></article><article className="panel"><div className="panel-head"><div><h2>Upcoming</h2><p>Next appointments</p></div><Link className="more" to={`${dashboardPath}/appointments`} aria-label="View appointments"><CalendarDays size={18}/></Link></div><Link className="appointment" to={`${dashboardPath}/appointments`}><div className="date-box"><strong>24</strong><span>AUG</span></div><div><strong>General consultation</strong><span>10:30 AM • Clinic</span></div></Link><Link className="appointment" to={`${dashboardPath}/appointments`}><div className="date-box"><strong>25</strong><span>AUG</span></div><div><strong>Follow-up appointment</strong><span>2:00 PM • Online</span></div></Link></article></section><section className="quick"><div><h2>Quick actions</h2><p>Common tasks for your portal.</p></div><div className="quick-grid"><Link to={`${dashboardPath}/patients`}><Users/>Find patient</Link><Link to={`${dashboardPath}/appointments`}><CalendarDays/>Book appointment</Link><Link to={`${dashboardPath}/records`}><ClipboardList/>New encounter</Link><Link to={`${dashboardPath}/payments`}><Wallet/>Record payment</Link><Link to={`${dashboardPath}/prescriptions`}><Stethoscope/>Create prescription</Link><Link to={`${dashboardPath}/messages`}><MessageSquare/>Open messages</Link><Link to={`${dashboardPath}/receipts`}><Receipt/>View receipts</Link><Link to={`${dashboardPath}/security`}><FileText/>Privacy settings</Link></div></section></main></div></div>}
