import {Link} from 'react-router-dom'; import {ArrowRight,Building2,Brain,CalendarDays,FlaskConical,HeartPulse,Home as HomeIcon,LockKeyhole,MapPin,MessageCircle,Pill,ShieldCheck,Stethoscope} from 'lucide-react'; import PublicNav from '../../components/PublicNav'; import PublicFooter from '../../components/PublicFooter';
export default function Home(){return <><PublicNav/><main><section className="trust-strip"><div><strong>One connected care network</strong><span>Built for people and the teams supporting them.</span></div><div className="trust-metrics"><span><b>8</b> care portals</span><span><b>24/7</b> digital access</span><span><b>1</b> patient journey</span></div></section>
<section className="hero hero-v3"><div className="hero-copy"><span className="eyebrow"><HeartPulse size={16}/> CONNECTED DIGITAL HEALTHCARE</span><h1>Care, with fewer <span>gaps.</span></h1><p>SAIED brings patients, doctors, nurses, pharmacies, clinics, hospitals and laboratories together through one secure healthcare network.</p><div className="hero-actions"><Link className="red-btn big" to="/services">Explore SAIED <ArrowRight/></Link><Link className="outline-btn big" to="/dashboard/patient">Patient Portal</Link></div><div className="hero-trust"><span><ShieldCheck/> Secure by design</span><span><MapPin/> Care near you</span></div></div><div className="hero-visual network-visual"><div className="network-orbit orbit-one"/><div className="network-orbit orbit-two"/><div className="network-lines"><i/><i/><i/><i/></div><div className="network-center"><HeartPulse size={29}/><strong>SAIED</strong><small>one care network</small></div><div className="care-node node-patient"><UserRoundIcon/><span>Patient</span></div><div className="care-node node-provider"><Stethoscope/><span>Provider</span></div><div className="care-node node-pharmacy"><Building2/><span>Pharmacy</span></div><div className="care-node node-lab"><FlaskIcon/><span>Laboratory</span></div><div className="floating-card"><div className="icon-round"><ShieldCheck/></div><div><strong>Private by default</strong><span>Access follows the patient</span></div></div></div></section>
<section className="section"><div className="section-head"><span className="eyebrow">ONE PLATFORM</span><h2>Everything connected in one place.</h2></div><div className="feature-grid">{[['Find healthcare','Search verified healthcare providers and facilities.','Stethoscope'],['Digital records','Connect eligible encounters and records with controlled access.','FileText'],['Pharmacy','Discover participating pharmacies and medicine services.','Building2'],['Pharmacist tools','Review prescriptions, manage stock and fulfil orders.','Pill']].map(([a,b])=><article className="feature" key={a}><div className="icon-round"><HeartPulse/></div><h3>{a}</h3><p>{b}</p><Link to="/services">Learn more →</Link></article>)}</div></section>
<section className="system-overview"><div className="system-intro"><span className="eyebrow">THE SAIED SYSTEM / 02</span><h2>One patient journey, from first search to follow-up.</h2><p>Designed for the moments between appointments too: finding care, sharing the right information, getting treatment, and staying connected.</p><Link className="red-btn" to="/services">Explore all portals <ArrowRight size={17}/></Link></div><div className="system-columns"><article><div className="system-icon"><HeartPulse/></div><span>01 / PATIENT CARE</span><h3>Care that follows the person.</h3><p>Profiles, appointments, home-care requests, records, prescriptions, lab results and digital receipts in one patient experience.</p><div className="system-tags"><b>Appointments</b><b>Medical records</b><b>Home visits</b></div></article><article><div className="system-icon"><Stethoscope/></div><span>02 / CLINICAL WORK</span><h3>Better tools for every care team.</h3><p>Doctors, nurses, pharmacists, clinics, hospitals and laboratories share the workflows they need without losing their boundaries.</p><div className="system-tags"><b>Encounters</b><b>Prescriptions</b><b>Laboratory</b></div></article><article><div className="system-icon"><LockKeyhole/></div><span>03 / PLATFORM TRUST</span><h3>Private by default.</h3><p>Role-based access, organization boundaries, provider verification, audit history and secure communications are part of the foundation.</p><div className="system-tags"><b>RLS access</b><b>Secure messaging</b><b>AI safety</b></div></article></div></section>
<section className="connect-strip"><div><span className="eyebrow">BUILT FOR THE WHOLE NETWORK</span><h2>Care is more than a consultation.</h2></div><div className="connect-items"><span><CalendarDays/> Appointments</span><span><Pill/> Pharmacy</span><span><MessageCircle/> Conversations</span><span><Brain/> AI assistance</span><span><Stethoscope/> Care teams</span></div></section>
<section className="care-story"><div className="care-story-image"><img src="https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=85" alt="Doctor consulting with a patient in a medical setting"/><span><ShieldCheck size={16}/> Verified care network</span></div><div className="care-story-copy"><span className="eyebrow">CARE THAT MOVES WITH YOU</span><h2>From a question to a clear next step.</h2><p>Find a provider, prepare for your visit, keep your records together and stay connected after care. SAIED makes the in-between moments easier to navigate.</p><div className="story-actions"><Link className="red-btn" to="/providers">Find care <ArrowRight size={17}/></Link><Link className="red-text" to="/ai">Talk to the assistant <ArrowRight size={15}/></Link></div></div></section>
<section className="cta"><div><span className="eyebrow light">SAIED FOR EVERYONE</span><h2>Choose the portal built for you.</h2><p>Patients and healthcare organizations use specialized dashboards while sharing one connected platform.</p></div><Link className="white-btn" to="/services">View Portals <ArrowRight/></Link></section>
</main><PublicFooter/></>}

function UserRoundIcon(){return <HeartPulse size={18}/>}
function FlaskIcon(){return <FlaskConical size={18}/>}
